### PR TITLE
Add mail support to Clean Blog theme

### PR DESCRIPTION
**Pull request by martinnabhan**
As you suggested I tried to add mail support through Rails, and quite surprisingly I managed to do it. Also disabled turbo links on the contact page as that made the javascript not load until the site was reloaded.

### CODE REVIEW

**Comment by martinnabhan** [comment]
Had some permission errors so had to close the request, but promptly fixed it so I'm reopening again, sorry.

**Comment by MrPowers** [comment]
Thanks for the pull request!  I am going to be traveling the next couple of days, but I will take a look at this next week.  Thanks!

**Comment by MrPowers** [comment]
It looks like some php stuff made its way into the code, so I'm going to have to clean this up a bit.  It's still on my radar, sorry for being slow...

Can you please send me an email (I can't email you because you don't have your email on your profile)?  My email is on my GitHub profile.  I'd like to see where you are at on your programming learning journey and see if there are some other project that you'd like to collaborate on.  Thanks!

**Comment by martinnabhan** [comment]
I think the permissions have been fixed! Is every file in the assets directory supposed to be non-executable (644)? Is this for security reasons? I had to make the folders 775 or else I couldn't get access to them without sudo, I guess that's normal? Please take a look!

**Comment by martinnabhan** [comment]
I've finished porting the Grayscale theme, sorry for taking so long!
This time I've hopefully given the right file permissions. Also, I couldn't include the Google Maps API script as it is in the original, instead I did an iframe like you did in the Freelancer theme, which I hope is OK.

Please take a look when you have time.

**Comment by MrPowers** [comment]
@MartinN13 - The clean blog stuff is going to need some work before it can be merged in, but we should be able to merge in the Grayscale stuff :smile: 

Can you please create a new pull request with the Grayscale theme?  The git cherry-pick command might help.  Thank you so much for the awesome help!

**Pull request closed without merging**
